# Specify csv files for time series and other options
time_series:
  default: # These values will be used unless specified in the entries below
    source: "ENTSOEdata_prelim.csv"
    csv_options: # These options are passed to CSV.read
        delim: ","
    timestamp: "Timestamp" # optional
    weight: 1 # weight of time series in objective / clustering
    interpolation_type: "linear" # or "constant" or don't specify
    sampling_time: "Hour(1)" # Only necessary if a timestamp is not given
    start: "2019-01-01T00:00:00Z" # Can also specify an integer which corresponds to rows in the .csv file

  Price:
    value_column: "Dayahead_price" # Column name to be read in csv file
  Solar:
    value_column: "Solar_profile"
  Wind:
    value_column: "Wind_profile"

method:
  options: # Method agnostic options
    mandatory_periods: [] # Leave empty to specify none
    total_periods: 364
    representative_periods: 3
    time_steps_per_period: 24
    sampling_time: "Hour(1)" # This is a DateTime format - for quarter hours, Hour(0.25)
  
  optimization:
    integral_weights: false
    binary_ordering: true
    equal_weights: false
    duration_curve_error:
      weight: 0.5
      number_bins: 40
      type: "absolute" # Or "absolute"

results:
  save_results: true
  # Options for exactly what to save here
  result_dir: 'results' # Relative to this file
  create_plots: true